plugins:
  override_smtp_enabled:
    default: false
  override_smtp_address:
    default: "smtp.gmail.com"
  override_smtp_port:
    default: 587
    min: 0
    max: 65537
  override_smtp_domain:
    default: "devn.cloud"
  override_smtp_username:
    default: "theaux@devn.cloud"
  override_smtp_password:
    default: "password"
    secret: true
  override_smtp_authentication_mode: 
    default: "plain"
  override_smtp_enable_starttls: 
    default: true
  override_smtp_enable_starttls_auto: 
    default: false  
  override_smtp_openssl_verify_mode: 
    default: "none"
  override_smtp_ssl: 
    default: ""
  override_smtp_tls: 
    default: ""
  override_smtp_open_timeout: 
    default: 5
  override_smtp_read_timeout: 
    default: 30
 
# override_smtp_enabled
# message.delivery_method.settings is like:
# {:address=>"localhost",
#  :port=>1025,
#  :domain=>"localhost.localdomain",
#  :user_name=>,
#  :password=>,
#  :authentication=plain>,
#  :enable_starttls=>true,
#  :enable_starttls_auto=>false,
#  :openssl_verify_mode=>none,
#  :ssl=>,
#  :tls=>,
#  :open_timeout=>5,
#  :read_timeout=>30,
#  :return_response=>true}
